databases:
  # PostgreSQL Database
  - name: cyberbullying-db
    plan: free
    region: frankfurt

services:

  # Backend API (FastAPI) - Docker ile Chrome desteği
  - type: web
    name: cyberbullying-backend
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cyberbullying-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: INSTAGRAM_USERNAME
        sync: false  # Manuel olarak girilecek
      - key: INSTAGRAM_PASSWORD
        sync: false  # Manuel olarak girilecek
      - key: GOOGLE_API_KEY
        sync: false  # Gemini API key - manuel olarak girilecek
      - key: FRONTEND_URL
        value: https://cyberbullying-frontend.onrender.com  # Frontend URL'inizi buraya ekleyin

  # Frontend (React)
  - type: web
    name: cyberbullying-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://cyberbullying-backend.onrender.com  # Backend URL'inizi buraya ekleyin

