databases:
  # PostgreSQL Database
  - name: cyberbullying-db
    plan: free

services:

  # Backend API (FastAPI) - Docker ile Chrome desteği
  - type: web
    name: cyberbullying-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cyberbullying-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: INSTAGRAM_USERNAME
        sync: false  # Manuel olarak girilecek
      - key: INSTAGRAM_PASSWORD
        sync: false  # Manuel olarak girilecek
      - key: GOOGLE_API_KEY
        sync: false  # Gemini API key - manuel olarak girilecek
      - key: FRONTEND_URL
        value: https://cyberbullying-frontend.onrender.com  # Frontend URL'inizi buraya ekleyin

  # Frontend (React) - Node Web Service
  - type: web
    name: cyberbullying-frontend
    env: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build && cd .."
    startCommand: "npx serve -s frontend/build -l $PORT"
    envVars:
      - key: REACT_APP_API_URL
        value: https://cyberbullying-backend-9391.onrender.com  # Backend'in GERÇEK URL'i

